#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

MAX_FEA_LEN = 181
DEFAULT_THRESHOLD = 0
IMAGE_CATAINS_FORBIDEN_FACE = -1
